### ISSUE TITLE
cosmic-comp error prevents login: "cosmic-comp exited with error code 137"

### ISSUE THREAD

**Issue by pchest** [pop-os/cosmic-comp#1562]
When I attempt to log in to Cosmic from the login screen, I get an error `cosmic-comp exited with error code 137`. I am not able to progress any further, so I have since resorted to using gnome as a temporary alternative DE. 

The error I see when I attempt to log in:

![Image](https://github.com/user-attachments/assets/1d6b22d2-4ae7-4120-8f80-69b392d70995)

System info:

<img width="947" height="1290" alt="Image" src="https://github.com/user-attachments/assets/2bea1e93-bc74-430d-b58c-6f4550d276c3" />

**Comment by Drakulix** [comment]
That log isn't and can't be complete, as cosmic-comp takes over the tty temporarily, which means log messages by it are lost and not rendered there.

Can you try to run it and then get the output of `journalctl --user _COMM=cosmic-comp -b0`? (You can do this in gnome afterwards, as long as you don't reboot).

**Comment by CosmoBunny** [comment]
Same happened to me. I updated the cosmic-comp via apt (Without restarting). I turn off the laptop (sleep) and then everything goes black. And then I force the turnoff and turn on the laptop. Afterward it stuck on cosmic-comp exited with error code  137 (128 + 9, basically SIGKILL 9 by OS). However I can exit through `CTRL + c`
I captured some journalctl logs (using the exact command from @Drakulix ) but it seems not helpful.

![IMG_20250804_171400.jpg](https://github.com/user-attachments/assets/f817fa04-24d6-4502-a919-503feea14132)

![IMG_20250804_171240.jpg](https://github.com/user-attachments/assets/e97edb27-dd0e-4b5c-b27f-0fae2a661496)

![IMG_20250804_171351.jpg](https://github.com/user-attachments/assets/18733ae2-ec36-45f1-96a0-abc64baeeccb)

![IMG_20250804_171315.jpg](https://github.com/user-attachments/assets/86db3904-87e8-486b-9eff-7f73aec31a9f)

**Comment by CosmoBunny** [comment]
There is a similar issue happening on Cosmic Session. But confusing scenario 

https://github.com/pop-os/cosmic-comp/issues/707

**Comment by Drakulix** [comment]
Please don't enter the command on a tty and take photos, just log into a different session and properly copy them from there. The appear to be incomplete, but even if they aren't this is barely readable.

**Comment by CosmoBunny** [comment]
here

[log.txt](https://github.com/user-attachments/files/21588581/log.txt)

```
Aug 05 07:44:19 pop-os cosmic-session[3663]: Starting cosmic-session
Aug 05 07:44:19 pop-os cosmic-session[3663]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
Aug 05 07:44:19 pop-os cosmic-session[3663]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
Aug 05 07:44:19 pop-os cosmic-session[3663]: cosmic-comp exited with error code 1
Aug 05 07:44:19 pop-os cosmic-session[3663]: draining stdin receiver before restarting process
Aug 05 07:44:19 pop-os cosmic-session[3663]: sleeping for 0ms before restarting process cosmic-comp (restart 0)
Aug 05 07:44:19 pop-os cosmic-session[3663]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
Aug 05 07:44:19 pop-os cosmic-session[3663]: process 'ProcessKey(1v1)' cancelled
Aug 05 07:44:19 pop-os cosmic-session[3663]: cosmic-comp exited with error code 137
Aug 05 07:50:22 pop-os cosmic-session[7683]: Starting cosmic-session
Aug 05 07:50:22 pop-os cosmic-session[7683]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
Aug 05 07:50:22 pop-os cosmic-session[7683]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
Aug 05 07:50:22 pop-os cosmic-session[7683]: cosmic-comp exited with error code 1
Aug 05 07:50:22 pop-os cosmic-session[7683]: draining stdin receiver before restarting process
Aug 05 07:50:22 pop-os cosmic-session[7683]: sleeping for 2ms before restarting process cosmic-comp (restart 0)
Aug 05 07:50:22 pop-os cosmic-session[7683]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
Aug 05 07:50:22 pop-os cosmic-session[7683]: process 'ProcessKey(1v1)' cancelled
Aug 05 07:50:22 pop-os cosmic-session[7683]: cosmic-comp exited with error code 137
```

**Comment by Drakulix** [comment]
I am sorry to bug you again, but this is just the cosmic-session log - not for cosmic-comp. Which command did you use exactly to get this?

**Comment by CosmoBunny** [comment]
On the above log, I used `journalctl --user _COMM=cosmic-session -b0 > log.txt`

here's for cosmic-comp (`journalctl --user _COMM=cosmic-comp -b0 > log.txt`):
```
Aug 05 08:14:46 pop-os cosmic-comp[3562]: Key-Binding 'Period' only matched case insensitive for "period"
Aug 05 08:14:46 pop-os cosmic-comp[3562]: Key-Binding 'Comma' only matched case insensitive for "comma"
Aug 05 08:14:46 pop-os cosmic-comp[3562]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 05 08:14:47 pop-os cosmic-comp[3562]: Unable to become drm master, assuming unprivileged mode
Aug 05 08:14:47 pop-os cosmic-comp[3562]: Failed to restore previous state. Error: Permission denied (os error 13)
Aug 05 08:14:47 pop-os cosmic-comp[3562]: Xwayland terminated: exit status: 1
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Key-Binding 'Period' only matched case insensitive for "period"
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Key-Binding 'Comma' only matched case insensitive for "comma"
Aug 05 15:53:47 pop-os cosmic-comp[54587]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Unable to become drm master, assuming unprivileged mode
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Failed to restore previous state. Error: Permission denied (os error 13)
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Xwayland terminated: exit status: 1
Aug 05 15:54:05 pop-os cosmic-comp[54856]: Key-Binding 'Period' only matched case insensitive for "period"
Aug 05 15:54:05 pop-os cosmic-comp[54856]: Key-Binding 'Comma' only matched case insensitive for "comma"
Aug 05 15:54:05 pop-os cosmic-comp[54856]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 05 15:54:05 pop-os cosmic-comp[54856]: Unable to become drm master, assuming unprivileged mode
Aug 05 15:54:05 pop-os cosmic-comp[54856]: Failed to restore previous state. Error: Permission denied (os error 13)
```

**Comment by nathanaelhoun** [comment]
Chiming into this thread as I have the same error as the OP.

I'm using cosmic on NixOS, with cosmic-comp built from https://github.com/pop-os/cosmic-comp/commit/bdef75dc8c9a4d51fe19ab4652fc06fc6f8ffe3b.

Here are my logs (`journalctl --user _COMM=cosmic-comp -b0` returns nothing so I copy-pasted what seems relevant from `journalctl --user`)

```
2025-08-05T11:12:12+02:00 framou cosmic-session[1765]: Starting cosmic-session
2025-08-05T11:12:12+02:00 framou cosmic-session[1765]: starting process ' COSMIC_SESSION_SOCK=13 cosmic-comp '
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: Key-Binding 'Period' only matched case insensitive for "period"
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: Key-Binding 'Comma' only matched case insensitive for "comma"
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: Unable to become drm master, assuming unprivileged mode
2025-08-05T11:12:13+02:00 framou .cosmic-comp-wrapped[1782]: Failed to restore previous state. Error: Permission denied (os error 13)
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: process ' COSMIC_SESSION_SOCK=13 cosmic-comp ' failed with code 1
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: cosmic-comp exited with error code 1
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: draining stdin receiver before restarting process
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: sleeping for 8ms before restarting process cosmic-comp (restart 0)
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: restarted process ' COSMIC_SESSION_SOCK=13 cosmic-comp ', now at 1 restarts
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: process 'ProcessKey(1v1)' cancelled
2025-08-05T11:12:13+02:00 framou cosmic-session[1765]: cosmic-comp exited with error code 137
```

**Comment by Drakulix** [comment]
Thank you all, unfortunately these logs aren't very helpful.

From what it looks like cosmic-comp is operating normally and killed by something external (if it isn't crashing, but none of the logs contain backtraces hinting at that).

To verify, that it is indeed operating normally, it would be helpful if somebody here is able to compile cosmic-comp from source, do a debug build and provide the additional logs this produces.

If it is killed by something else, a full journal logs might help to pin point the cause (e.g. memory pressure), but that might contain some privacy-sensitive information: `journalctl -b0`.

**Comment by CosmoBunny** [comment]
I tried all commit of cosmic-comp and cosmic-sesssion but it doesn't work. I think cosmic-comp is not the issue, there something different problem.

From `journalctl -b0` (at same time as executing cosmic-comp)
```
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSource/faststream
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSource/faststream_duplex
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSink/opus_05
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSource/opus_05
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Aug 05 15:53:46 pop-os bluetoothd[1059]: Endpoint registered: sender=:1.378 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Aug 05 15:53:46 pop-os wireplumber[54517]: wp-device: SPA handle 'api.libcamera.enum.manager' could not be loaded; is it installed?
Aug 05 15:53:46 pop-os wireplumber[54517]: s-monitors-libcamera: PipeWire's libcamera SPA plugin is missing or broken. Some camera types may not be su>
Aug 05 15:53:46 pop-os rtkit-daemon[1651]: Supervising 14 threads of 8 processes of 2 users.
Aug 05 15:53:46 pop-os rtkit-daemon[1651]: Supervising 14 threads of 8 processes of 2 users.
Aug 05 15:53:46 pop-os fluidsynth[54514]: fluidsynth: warning: Failed to set thread to high priority
Aug 05 15:53:46 pop-os fluidsynth[54514]: FluidSynth runtime version 2.3.4
Aug 05 15:53:46 pop-os fluidsynth[54514]: Copyright (C) 2000-2023 Peter Hanappe and others.
Aug 05 15:53:46 pop-os fluidsynth[54514]: Distributed under the LGPL license.
Aug 05 15:53:46 pop-os fluidsynth[54514]: SoundFont(R) is a registered trademark of Creative Technology Ltd.
Aug 05 15:53:46 pop-os systemd[54493]: fluidsynth.service: Failed with result 'protocol'.
Aug 05 15:53:46 pop-os systemd[54493]: Failed to start fluidsynth.service - FluidSynth Daemon.
Aug 05 15:53:46 pop-os systemd[54493]: Reached target default.target - Main User Target.
Aug 05 15:53:47 pop-os cosmic-session[54544]: Starting cosmic-session
Aug 05 15:53:47 pop-os cosmic-session[54544]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
Aug 05 15:53:47 pop-os systemd[1]: ollama.service: Scheduled restart job, restart counter is at 4575.
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Key-Binding 'Period' only matched case insensitive for "period"
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Key-Binding 'Comma' only matched case insensitive for "comma"
Aug 05 15:53:47 pop-os systemd[1]: Started ollama.service - Ollama Service.
Aug 05 15:53:47 pop-os ollama[54590]: Couldn't find '/usr/share/ollama/.ollama/id_ed25519'. Generating new private key.
Aug 05 15:53:47 pop-os ollama[54590]: Error: could not create directory mkdir /usr/share/ollama: permission denied
Aug 05 15:53:47 pop-os systemd[1]: ollama.service: Main process exited, code=exited, status=1/FAILURE
Aug 05 15:53:47 pop-os systemd[1]: ollama.service: Failed with result 'exit-code'.
Aug 05 15:53:47 pop-os cosmic-comp[54587]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, mess>
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Unable to become drm master, assuming unprivileged mode
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Failed to restore previous state. Error: Permission denied (os error 13)
Aug 05 15:53:47 pop-os cosmic-comp[54587]: Xwayland terminated: exit status: 1
Aug 05 15:53:47 pop-os cosmic-session[54544]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 1
Aug 05 15:53:47 pop-os cosmic-session[54544]: cosmic-comp exited with error code 1
Aug 05 15:53:47 pop-os cosmic-session[54544]: draining stdin receiver before restarting process
Aug 05 15:53:47 pop-os cosmic-session[54544]: sleeping for 8ms before restarting process cosmic-comp (restart 0)
Aug 05 15:53:47 pop-os cosmic-session[54544]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
Aug 05 15:53:47 pop-os cosmic-session[54544]: process 'ProcessKey(1v1)' cancelled
Aug 05 15:53:47 pop-os cosmic-session[54544]: cosmic-comp exited with error code 137
```

I think I should refresh install and check it again.

**Comment by CosmoBunny** [comment]
strange, I can open in Gnome-wayland but can't able to open direct

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/f2434126-e4ec-46fb-8adf-9ed4e9293ff6" />

There is something messed with cosmic-session command

**Comment by luca-trigili** [comment]
Cosmic- comp![PXL_20250805_123307734.RAW-01.MP.COVER.jpg](https://github.com/user-attachments/assets/bb5832ef-8624-437e-9fca-236fd8fd243d)

**Comment by ids1024** [comment]
I seem to be seeing an issue like this now.

Running in a tty and redirecting output, it shows:

```
2025-08-05T14:29:21.009538Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Period' only matched case insensitive for "period"
2025-08-05T14:29:21.009572Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Comma' only matched case insensitive for "comma"
2025-08-05T14:29:21.009896Z ERROR cosmic_settings_config::window_rules: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-08-05T14:29:21.048280Z  WARN smithay::backend::drm::device::fd: Unable to become drm master, assuming unprivileged mode
2025-08-05T14:29:21.090380Z  WARN smithay::backend::drm::device::fd: Unable to become drm master, assuming unprivileged mode
2025-08-05T14:29:21.148241Z ERROR smithay::backend::drm::device::atomic: Failed to restore previous state. Error: Permission denied (os error 13)
2025-08-05T14:29:21.148612Z ERROR smithay::backend::drm::device::atomic: Failed to restore previous state. Error: Permission denied (os error 13)
Error: Backend initialized without output
2025-08-05T14:29:21.157026Z ERROR smithay::xwayland::xserver: Xwayland terminated: exit status: 1
```

It seems `Error: Backend initialized without output` isn't being logged to journald, just printed, which is making the journalctl logs a little confusing here.

Maybe due to some update to a component other than cosmic-comp? But sway and anvil start fine.

**Comment by ids1024** [comment]
In a debug build from `master`:

```
2025-08-05T14:36:53.245161Z  INFO cosmic_comp::logger: Version: 0.1.0
2025-08-05T14:36:53.245310Z  INFO cosmic_comp: Cosmic starting up!
2025-08-05T14:36:53.245630Z  INFO smithay::wayland::socket: Created new socket name=Some("wayland-2")
2025-08-05T14:36:53.245688Z  INFO cosmic_comp: Listening on "wayland-2"
2025-08-05T14:36:53.247897Z  INFO i18n_embed::requester: Current Locale: [LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }]
2025-08-05T14:36:53.247988Z  INFO i18n_embed: Selecting translations for domain "cosmic_comp"
2025-08-05T14:36:53.251595Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Period' only matched case insensitive for "period"
2025-08-05T14:36:53.251651Z  WARN cosmic_settings_config::shortcuts::sym: Key-Binding 'Comma' only matched case insensitive for "comma"
2025-08-05T14:36:53.252827Z ERROR cosmic_settings_config::window_rules: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
2025-08-05T14:36:53.290538Z DEBUG smithay::backend::session::libseat: Enable callback called
2025-08-05T14:36:53.298375Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event8" type="libseat" path="/dev/input/event8" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.299704Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event3" type="libseat" path="/dev/input/event3" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.300959Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event0" type="libseat" path="/dev/input/event0" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.302274Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event1" type="libseat" path="/dev/input/event1" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.303192Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event2" type="libseat" path="/dev/input/event2" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.304111Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event11" type="libseat" path="/dev/input/event11" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.305014Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.305376Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event12" type="libseat" path="/dev/input/event12" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.306268Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.306603Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event13" type="libseat" path="/dev/input/event13" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.307557Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.307902Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event14" type="libseat" path="/dev/input/event14" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.308800Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.309127Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event10" type="libseat" path="/dev/input/event10" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.310010Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.310390Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event6" type="libseat" path="/dev/input/event6" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.311878Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event7" type="libseat" path="/dev/input/event7" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.313617Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event15" type="libseat" path="/dev/input/event15" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.314535Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 44 } type="libseat" fd=OwnedFd { fd: 44 }
2025-08-05T14:36:53.314880Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event16" type="libseat" path="/dev/input/event16" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.315789Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 44 } type="libseat" fd=OwnedFd { fd: 44 }
2025-08-05T14:36:53.316120Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event4" type="libseat" path="/dev/input/event4" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.318016Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event5" type="libseat" path="/dev/input/event5" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.320654Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/input/event9" type="libseat" path="/dev/input/event9" _flags=OFlags(NONBLOCK | RDWR | CLOEXEC)
2025-08-05T14:36:53.321675Z  INFO backend_libinput: smithay::backend::libinput: Initializing a libinput backend
2025-08-05T14:36:53.322987Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/dri/card1" type="libseat" path="/dev/dri/card1" _flags=OFlags(NONBLOCK | RDWR | NOCTTY | CLOEXEC)
2025-08-05T14:36:53.323345Z  WARN smithay::backend::drm::device::fd: Unable to become drm master, assuming unprivileged mode
2025-08-05T14:36:53.323428Z  INFO drm_device: smithay::backend::drm::device: DrmDevice initializing device=Some("/dev/dri/card1")
2025-08-05T14:36:53.360044Z DEBUG smithay::backend::egl::display: Supported EGL client extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_MESA_platform_surfaceless", "EGL_EXT_explicit_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_KHR_platform_gbm", "EGL_MESA_platform_gbm", "EGL_EXT_platform_xcb"]
2025-08-05T14:36:53.360124Z DEBUG smithay::backend::egl::display: Trying EGL platform: PLATFORM_GBM_KHR
2025-08-05T14:36:53.360165Z  INFO smithay::backend::egl::display: Successfully selected EGL platform: PLATFORM_GBM_KHR
2025-08-05T14:36:53.362106Z  INFO smithay::backend::egl::display: EGL Initialized
2025-08-05T14:36:53.362133Z  INFO smithay::backend::egl::display: EGL Version: (1, 5)
2025-08-05T14:36:53.362177Z  INFO smithay::backend::egl::display: Supported EGL display extensions: ["EGL_ANDROID_blob_cache", "EGL_ANDROID_native_fence_sync", "EGL_EXT_buffer_age", "EGL_EXT_config_select_group", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_EXT_protected_surface", "EGL_EXT_query_reset_notification_strategy", "EGL_EXT_surface_compression", "EGL_IMG_context_priority", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_context_flush_control", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_gl_interop", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_MESA_x11_native_visual_id", "EGL_WL_bind_wayland_display", ""]
2025-08-05T14:36:53.364335Z  INFO egl:egl_context: smithay::backend::egl::context: EGL context created priority=Some(High) native="/dev/dri/card1" platform="PLATFORM_GBM_KHR" version=(1, 5) ptr=95218360858384
2025-08-05T14:36:53.366202Z  INFO smithay::wayland::socket: Created new socket name=Some("wayland-2-renderD129")
2025-08-05T14:36:53.366256Z  INFO cosmic_comp::backend::kms::socket: Added gpu-specific socket. socket_name="wayland-2-renderD129" render_node=DrmNode { dev: 57985, ty: Render }
2025-08-05T14:36:53.367506Z  INFO new: smithay::output: Creating new Output name="eDP-1" name="eDP-1" physical=PhysicalProperties { size: Size<smithay::utils::geometry::Raw> { w: 310, h: 170 }, subpixel: Unknown, make: "Sharp Corporation", model: "LQ140M1JW49" }
2025-08-05T14:36:53.368697Z DEBUG backend_session:open: smithay::backend::session::libseat: Opening device: "/dev/dri/card0" type="libseat" path="/dev/dri/card0" _flags=OFlags(NONBLOCK | RDWR | NOCTTY | CLOEXEC)
2025-08-05T14:36:53.369124Z  WARN smithay::backend::drm::device::fd: Unable to become drm master, assuming unprivileged mode
2025-08-05T14:36:53.369217Z  INFO drm_device: smithay::backend::drm::device: DrmDevice initializing device=Some("/dev/dri/card0")
2025-08-05T14:36:53.370563Z DEBUG smithay::backend::egl::display: Supported EGL client extensions: ["EGL_EXT_platform_base", "EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_KHR_platform_x11", "EGL_EXT_platform_x11", "EGL_EXT_platform_device", "EGL_MESA_platform_surfaceless", "EGL_EXT_explicit_device", "EGL_KHR_platform_wayland", "EGL_EXT_platform_wayland", "EGL_KHR_platform_gbm", "EGL_MESA_platform_gbm", "EGL_EXT_platform_xcb"]
2025-08-05T14:36:53.370595Z DEBUG smithay::backend::egl::display: Trying EGL platform: PLATFORM_GBM_KHR
2025-08-05T14:36:53.378054Z  INFO smithay::backend::egl::display: Successfully selected EGL platform: PLATFORM_GBM_KHR
2025-08-05T14:36:53.385255Z  INFO smithay::backend::egl::display: EGL Initialized
2025-08-05T14:36:53.385283Z  INFO smithay::backend::egl::display: EGL Version: (1, 5)
2025-08-05T14:36:53.385324Z  INFO smithay::backend::egl::display: Supported EGL display extensions: ["EGL_ANDROID_native_fence_sync", "EGL_EXT_buffer_age", "EGL_EXT_client_sync", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_MESA_image_dma_buf_export", "EGL_EXT_output_base", "EGL_EXT_output_drm", "EGL_EXT_protected_content", "EGL_EXT_stream_consumer_egloutput", "EGL_EXT_stream_acquire_mode", "EGL_EXT_sync_reuse", "EGL_IMG_context_priority", "EGL_KHR_config_attribs", "EGL_KHR_create_context_no_error", "EGL_KHR_context_flush_control", "EGL_KHR_create_context", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_partial_update", "EGL_KHR_swap_buffers_with_damage", "EGL_KHR_no_config_context", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_reusable_sync", "EGL_KHR_stream", "EGL_KHR_stream_attrib", "EGL_KHR_stream_consumer_gltexture", "EGL_KHR_stream_cross_process_fd", "EGL_KHR_stream_fifo", "EGL_KHR_stream_producer_eglsurface", "EGL_KHR_surfaceless_context", "EGL_KHR_wait_sync", "EGL_NV_nvrm_fence_sync", "EGL_NV_quadruple_buffer", "EGL_NV_stream_consumer_eglimage", "EGL_NV_stream_cross_display", "EGL_NV_stream_cross_object", "EGL_NV_stream_cross_process", "EGL_NV_stream_cross_system", "EGL_NV_stream_dma", "EGL_NV_stream_flush", "EGL_NV_stream_metadata", "EGL_NV_stream_remote", "EGL_NV_stream_reset", "EGL_NV_stream_socket", "EGL_NV_stream_socket_inet", "EGL_NV_stream_socket_unix", "EGL_NV_stream_sync", "EGL_NV_stream_fifo_next", "EGL_NV_stream_fifo_synchronous", "EGL_NV_stream_consumer_gltexture_yuv", "EGL_NV_stream_attrib", "EGL_NV_stream_origin", "EGL_NV_system_time", "EGL_NV_output_drm_flip_event", "EGL_NV_triple_buffer", "EGL_NV_robustness_video_memory_purge", "EGL_EXT_present_opaque", "EGL_WL_bind_wayland_display", "EGL_WL_wayland_eglstream"]
2025-08-05T14:36:53.399380Z  INFO egl:egl_context: smithay::backend::egl::context: EGL context created priority=Some(High) native="/dev/dri/card0" platform="PLATFORM_GBM_KHR" version=(1, 5) ptr=95218358579585
2025-08-05T14:36:53.402317Z  INFO smithay::wayland::socket: Created new socket name=Some("wayland-2-renderD128")
2025-08-05T14:36:53.402359Z  INFO cosmic_comp::backend::kms::socket: Added gpu-specific socket. socket_name="wayland-2-renderD128" render_node=DrmNode { dev: 57984, ty: Render }
2025-08-05T14:36:53.406952Z  INFO cosmic_comp::backend::kms: Using renderD129 as primary gpu for rendering.
2025-08-05T14:36:53.407062Z DEBUG smithay::xwayland::x11_sockets: Attempting to aquire an X11 display lock display=0
2025-08-05T14:36:53.407135Z DEBUG smithay::xwayland::x11_sockets: Failed to acquire lock display=0
2025-08-05T14:36:53.407177Z DEBUG smithay::xwayland::x11_sockets: Attempting to aquire an X11 display lock display=1
2025-08-05T14:36:53.407217Z DEBUG smithay::xwayland::x11_sockets: Failed to acquire lock display=1
2025-08-05T14:36:53.407249Z DEBUG smithay::xwayland::x11_sockets: Attempting to aquire an X11 display lock display=2
2025-08-05T14:36:53.407385Z DEBUG smithay::xwayland::x11_sockets: X11 lock acquired display=2
2025-08-05T14:36:53.407518Z  INFO smithay::xwayland::xserver: spawning XWayland instance
2025-08-05T14:36:53.413013Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 37 } type="libseat" fd=OwnedFd { fd: 37 }
2025-08-05T14:36:53.413450Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 38 } type="libseat" fd=OwnedFd { fd: 38 }
2025-08-05T14:36:53.413698Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 39 } type="libseat" fd=OwnedFd { fd: 39 }
2025-08-05T14:36:53.413944Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 40 } type="libseat" fd=OwnedFd { fd: 40 }
2025-08-05T14:36:53.414185Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 41 } type="libseat" fd=OwnedFd { fd: 41 }
2025-08-05T14:36:53.414426Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 42 } type="libseat" fd=OwnedFd { fd: 42 }
2025-08-05T14:36:53.414656Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 43 } type="libseat" fd=OwnedFd { fd: 43 }
2025-08-05T14:36:53.414893Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 44 } type="libseat" fd=OwnedFd { fd: 44 }
2025-08-05T14:36:53.415127Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 45 } type="libseat" fd=OwnedFd { fd: 45 }
2025-08-05T14:36:53.415371Z DEBUG backend_session:close: smithay::backend::session::libseat: Closing device: OwnedFd { fd: 46 } type="libseat" fd=OwnedFd { fd: 46 }
2025-08-05T14:36:53.415860Z DEBUG smithay::backend::session::libseat: Closing seat
2025-08-05T14:36:53.434273Z DEBUG drm_device:drm_atomic: smithay::backend::drm::device::atomic: Device still active, trying to restore previous state device=Some("/dev/dri/card1")
2025-08-05T14:36:53.434764Z ERROR drm_device:drm_atomic: smithay::backend::drm::device::atomic: Failed to restore previous state. Error: Permission denied (os error 13) device=Some("/dev/dri/card1")
2025-08-05T14:36:53.434856Z  INFO smithay::backend::drm::device::fd: Dropping device: Some("/dev/dri/card1")
2025-08-05T14:36:53.435339Z DEBUG drm_device:drm_atomic: smithay::backend::drm::device::atomic: Device still active, trying to restore previous state device=Some("/dev/dri/card0")
2025-08-05T14:36:53.435515Z ERROR drm_device:drm_atomic: smithay::backend::drm::device::atomic: Failed to restore previous state. Error: Permission denied (os error 13) device=Some("/dev/dri/card0")
2025-08-05T14:36:53.435559Z  INFO smithay::backend::drm::device::fd: Dropping device: Some("/dev/dri/card0")
2025-08-05T14:36:53.435771Z  INFO smithay::xwayland::x11_sockets: Cleaning up X11 lock.
Error: Backend initialized without output
2025-08-05T14:36:53.444334Z ERROR smithay::xwayland::xserver: Xwayland terminated: exit status: 1
```

The "Closing seat" and related messages don't look correct...

**Comment by Drakulix** [comment]
> The "Closing seat" and related messages don't look correct...

No, that indicates a tty switch or similar, before we finished initializing.. Are there maybe some log messages from systemd-logind somewhere? Or can we enable more logging from libseat?

**Comment by ids1024** [comment]
> No, that indicates a tty switch or similar, before we finished initializing.. 

This is just starting `cosmic-comp` on a tty, and running until it terminates. So no tty switch.

Noting seems to be logged to journald here by anything other than cosmic-comp. Not sure if there's a way to get more logging.

It also seems odd that anvil starts fine (but older commits of cosmic-comp seem to have the same issue); it should be using libseat in much the same way I thought...

**Comment by ids1024** [comment]
It looks like this is related to output configuration (and likely https://github.com/pop-os/cosmic-comp/pull/1547 disabling an output, but nothing re-enabling it?). 

Anyone running into this can try backing up `~/.local/state/cosmic-comp/outputs.ron` and seeing if cosmic-comp starts properly when that file doesn't already exist.

**Comment by ManuSomvanshi** [comment]
> It looks like this is related to output configuration (and likely [#1547](https://github.com/pop-os/cosmic-comp/pull/1547) disabling an output, but nothing re-enabling it?).
> 
> Anyone running into this can try backing up `~/.local/state/cosmic-comp/outputs.ron` and seeing if cosmic-comp starts properly when that file doesn't already exist.

Hi! I had the same issue today. It does work after removing the `outputs.ron` file.  

Edit: Here are my `cosmic-comp` logs

```
Aug 06 01:27:22 pop-os cosmic-comp[2589]: Key-Binding 'Period' only matched case insensitive for "period"
Aug 06 01:27:22 pop-os cosmic-comp[2589]: Key-Binding 'Comma' only matched case insensitive for "comma"
Aug 06 01:27:22 pop-os cosmic-comp[2589]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 06 01:27:22 pop-os cosmic-comp[2589]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Aug 06 01:27:22 pop-os cosmic-comp[2589]: Unable to become drm master, assuming unprivileged mode
Aug 06 01:27:33 pop-os cosmic-comp[2589]: CosmicTk config entry error
Aug 06 01:27:33 pop-os cosmic-comp[2589]: CosmicTk config entry error
Aug 06 01:41:20 pop-os cosmic-comp[2589]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Aug 06 01:41:20 pop-os cosmic-comp[2589]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Aug 06 01:41:20 pop-os cosmic-comp[2589]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
```

**Comment by Drakulix** [comment]
Can somebody please open their broken outputs.ron file please that causes issues?

**Comment by nathanaelhoun** [comment]
Removing `outputs.ron` also fixed the issue on my computer, thanks for the tip!

Here is the broken file, before removal: [`outputs.ron`](https://github.com/user-attachments/files/21606875/outputs.ron.txt)

**Comment by ids1024** [comment]
The `outputs.ron` file I had when this was failing includes this, as the configuration when only the `eDP-1` output is connected:

```
        [
            (
                connector: "eDP-1",
                make: "Sharp Corporation",
                model: "LQ140M1JW49",
            ),
        ]: [
            (
                mode: ((1920, 1080), Some(143981)),
                vrr: r#true,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#false,
                max_bpc: Some(16),
                xwayland_primary: false,
            ),
        ],
```

So it does seem `enabled` is set to `false` in the persisted config, for whatever reason. And cosmic-comp terminates on start in such a case, instead of forcing the output enabled, or running without outputs.

**Comment by ids1024** [comment]
The `InputEvent::SwitchToggle` handler seems to updated the `enabled` field of the `RefCell<OutputConfig>>` udata associated with the output. It doesn't persist this configuration, but it looks like if `Config::write_outputs()` is later called anywhere, that gets persisted to the configuration file? And the switch handler applies even if this is the only connected output (cosmic-comp handles removal of the last output, but expects at least one output at start).

**Comment by atiq-cs** [comment]
> Can somebody please open their broken outputs.ron file please that causes issues?

Here you go @Drakulix , (left side one is the corrupt one, right side one is the current working version (auto recreated by cosmic))

<img width="3150" height="1008" alt="Image" src="https://github.com/user-attachments/assets/3c74f5b5-7a1d-46c3-8693-d94ecc265ed2" />

(I will update this message with more details and logs )

**Comment by CosmoBunny** [comment]
> strange, I can open in Gnome-wayland but can't able to open direct
> 
> <img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/f2434126-e4ec-46fb-8adf-9ed4e9293ff6" />
> 
> There is something messed with cosmic-session command

As I mentioned above how cosmic-session works on gnome wayland. It was running like Virtual Wayland Display.The problem was linked about Display management where there are some misconfugured on `~/.local/state/cosmic-comp/output.ron` `[]:[]` or no primary wayland display make infinite VRAM alloc that's why it throw 137 (128+9) SIGKILL OOM (out of memory)

So, it finally fixed it after removing `~/.local/state/cosmic-comp/outputs.ron`. this will create fresh `outputs.ron` while login cosmic-session

**Comment by pchest** [comment]
Thanks for the detailed discussion, everyone! Removing `~/.local/state/cosmic-comp/output.ron`, as suggested by @nathanaelhoun and @CosmoBunny,  enabled me to log in to cosmic without any issue. Thank you @Drakulix for looking into this. I'll mark this issue as completed.

**Comment by Drakulix** [comment]
We still haven't fixed what broke the config in the first place, nor should the config prevent cosmic-comp from starting. Re-opening until we figured that out.

**Comment by CosmoBunny** [comment]
Maybe it cause by updating package or misconfigured by cosmic-settings. IDK
`outputs.ron` (old)
```
(
    config: {
        []: [],
        [
            (
                connector: "X11-0",
                make: "COSMIC",
                model: "X11-0",
            ),
        ]: [
            (
                mode: ((1280, 800), None),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "eDP-1",
                make: "Samsung Display Corp.",
                model: "0x5441",
            ),
        ]: [
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#false,
                max_bpc: Some(12),
                xwayland_primary: true,
            ),
        ],
        [
            (
                connector: "HDMI-A-1",
                make: "Unknown",
                model: "SKK181",
            ),
            (
                connector: "eDP-1",
                make: "Unknown",
                model: "21569",
            ),
        ]: [
            (
                mode: ((1280, 720), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1366, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "eDP-1",
                make: "Unknown",
                model: "21569",
            ),
        ]: [
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "HDMI-A-1",
                make: "Unknown",
                model: "MStar Demo",
            ),
            (
                connector: "eDP-1",
                make: "Unknown",
                model: "21569",
            ),
        ]: [
            (
                mode: ((1920, 1080), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1366, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "HDMI-A-1",
                make: "Unknown",
                model: "LG TV",
            ),
            (
                connector: "eDP-1",
                make: "Unknown",
                model: "21569",
            ),
        ]: [
            (
                mode: ((1360, 768), Some(60015)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1366, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "WINIT-0",
                make: "COSMIC",
                model: "WINIT-0",
            ),
        ]: [
            (
                mode: ((1280, 707), None),
                vrr: r#true,
                scale: 1.0,
                transform: Flipped180,
                position: (0, 0),
                enabled: r#true,
                xwayland_primary: false,
            ),
        ],
        [
            (
                connector: "HDMI-A-1",
                make: "LG Electronics",
                model: "LG TV",
            ),
            (
                connector: "eDP-1",
                make: "Samsung Display Corp.",
                model: "0x5441",
            ),
        ]: [
            (
                mode: ((1360, 768), Some(60015)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1366, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: true,
            ),
        ],
    },
)
```
`outputs.ron` (fresh - after removing old and reboot)
```
(
    config: {
        [
            (
                connector: "HDMI-A-1",
                make: "LG Electronics",
                model: "LG TV",
            ),
            (
                connector: "eDP-1",
                make: "Samsung Display Corp.",
                model: "0x5441",
            ),
        ]: [
            (
                mode: ((1360, 768), Some(60015)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (1366, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: false,
            ),
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: true,
            ),
        ],
        [
            (
                connector: "eDP-1",
                make: "Samsung Display Corp.",
                model: "0x5441",
            ),
        ]: [
            (
                mode: ((1366, 768), Some(60000)),
                vrr: r#false,
                scale: 1.0,
                transform: Normal,
                position: (0, 0),
                enabled: r#true,
                max_bpc: Some(12),
                xwayland_primary: true,
            ),
        ],
    },
)
```

I notice one thing is new version of `outputs.ron`. `[]:[]` is not placed at first (and not anywhere)

**Comment by loganmancuso** [comment]
removing the `~/.local/state/cosmic-comp/outputs.ron` fixed this issue. For more context, in my case it was human error. I was in the process of closing the lid of my laptop when I suddenly realized I needed to do one more thing. The screen had flickered off then would not come back on. I closed the lid fully and let it sit for a moment and reopened the lid. the screen came back on but I then started getting this error. 

To fix it I dropped into a shell using ctrl+alt+f3, logged in, removed the file and returned to the login using ctrl+alt+f1. Logged in and the issue was fixed. thanks to everyone for documenting this!

**Comment by Drakulix** [comment]
I was able to consistently reproduce this by:
1. attaching an external display
2. closing the lid
3. detaching the display and wait for the laptop to reach standby
4. opening the lid / resume -> black screen
5. restarting cosmic-comp now will exit immediately

I am still trying to figure out the cleanest way to fix this, since the whole lid-close/standby logic is a bit racy (multiple different endpoints may get events in a very short timeframe) and I think there might even be some overlap with other issues, where e.g. outputs wouldn't turn on anymore after a kvm switch.

But the issue has been identified and work is under way. Thanks everybody who contributed to finding the cause.

**Comment by CosmoBunny** [comment]
@Drakulix 
We love your efforts on `cosmic-comp`. We hope for a stable version doesn't deal with issues.

**Comment by atiq-cs** [comment]
> I was able to consistently reproduce this by:
> 
> 1. attaching an external display
> 2. closing the lid
> 3. detaching the display and wait for the laptop to reach standby
> 4. opening the lid / resume -> black screen
> 5. restarting cosmic-comp now will exit immediately

Sounds right except that I never attached an external display to my laptop to repro it.

**Comment by pchest** [comment]
@atiq-cs Same here. I haven't used an external display and still encountered the issue after resuming from sleep mode.

**Comment by Drakulix** [comment]
Should be fixed with https://github.com/pop-os/cosmic-comp/pull/1570 now. Please comment, if you still see any issues related to laptops, lid-closing and suspend!

**Comment by atiq-cs** [comment]
Here are the logs from my system before the fix, in case they are ever needed in future.

[cosmic-comp_error-08-06.tar.gz](https://github.com/user-attachments/files/21910730/cosmic-comp_error-08-06.tar.gz)
