### ISSUE TITLE
Can't enable/disable internal / external monitors

### ISSUE THREAD

**Issue by shawn111** [pop-os/cosmic-comp#422]
It seem related with https://github.com/pop-os/cosmic-comp/issues/33

My display information is correct, it shows there are two monitor.
I can see the "Enable display" switch, however it seems no function.
Click it to disable seems return to enable quickly.

[screen-capture.webm](https://github.com/pop-os/cosmic-comp/assets/346761/ba93d933-99e7-488a-a2b5-ae9c75a1d706)

If I run cosmic-settings displays from terminal, it show some errors.
```
╰─❯ cosmic-settings displays
  ERROR  Failed to load Panel system config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/panel/mod.rs:82 on main

  ERROR  Failed to load Panel system config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/panel/mod.rs:82 on main

  ERROR  Error when loading Panel container config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Failed to load Dock system config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/dock/mod.rs:124 on main

  ERROR  Failed to load Dock system config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/dock/mod.rs:124 on main

  ERROR  Error when loading Panel container config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: RonSpanned(SpannedError { code: TrailingCharacters, position: Position { line: 1, col: 13 } })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Error when loading Panel container config., err: GetKey("opacity", Os { code: 2, kind: NotFound, message: "No such file or directory" })
    at cosmic-settings/src/pages/desktop/panel/inner.rs:62 on main

  ERROR  Failed to read config 'workspaces', err: NoConfigDirectory
    at cosmic-settings/src/pages/desktop/workspaces.rs:39 on main

  ERROR  Failed to read config 'show_workspace_name', err: NoConfigDirectory
    at cosmic-settings/src/pages/desktop/workspaces.rs:49 on main

  ERROR  Failed to read config 'show_workspace_number', err: NoConfigDirectory
    at cosmic-settings/src/pages/desktop/workspaces.rs:53 on main

  ERROR  Failed to read config 'input_default', why: NoConfigDirectory
    at cosmic-settings/src/pages/input/mod.rs:67 on main

  ERROR  Failed to read config 'input_touchpad', why: NoConfigDirectory
    at cosmic-settings/src/pages/input/mod.rs:67 on main

  ERROR  Failed to read config 'military_time', err: NoConfigDirectory
    at cosmic-settings/src/pages/time/date.rs:38 on main

  ERROR  Failed to read config 'first_day_of_week', err: NoConfigDirectory
    at cosmic-settings/src/pages/time/date.rs:42 on main

  ERROR  Failed to read config 'show_date_in_top_panel', err: NoConfigDirectory
    at cosmic-settings/src/pages/time/date.rs:46 on main

  ERROR  error fetching graphics switching mode, why: Os { code: 2, kind: NotFound, message: "No such file or directory" }
    at cosmic-settings/src/pages/display/mod.rs:350 on main

Error: "configuration failed"
  ERROR  error fetching graphics switching mode, why: Os { code: 2, kind: NotFound, message: "No such file or directory" }
    at cosmic-settings/src/pages/display/mod.rs:350 on main
```

CPU/GPU: AMD Ryzen 5 PRO 7530U with Radeon Graphics
kernel: 6.8.5-301.fc40.x86_64

```
cosmic-panel-0.1.0~20240411.23-1.fc40.x86_64
cosmic-app-library-0.1.0~20240411.23-1.fc40.x86_64
cosmic-notifications-0.1.0~20240411.23-1.fc40.x86_64
cosmic-osd-0.1.0~20240411.23-1.fc40.x86_64
cosmic-randr-0.1.0~20240412.00-1.fc40.x86_64
cosmic-screenshot-0.1.0~20240411.23-1.fc40.x86_64
cosmic-settings-0.1.0~20240411.23-1.fc40.x86_64
cosmic-settings-daemon-0.1.0~20240411.23-1.fc40.x86_64
cosmic-launcher-0.1.0~20240411.23-1.fc40.x86_64
xdg-desktop-portal-cosmic-0.1.0~20240412.01-1.fc40.x86_64
cosmic-store-0.1.0~20240411.23-1.fc40.x86_64
cosmic-edit-0.1.0~20240411.23-1.fc40.x86_64
cosmic-files-0.1.0~20240412.01-1.fc40.x86_64
cosmic-term-0.1.0~20240411.23-1.fc40.x86_64
cosmic-icons-0.1.0~20240411.23-1.fc40.x86_64
cosmic-applets-0.1.0~20240411.23-1.fc40.x86_64
cosmic-bg-0.1.0~20240411.23-1.fc40.x86_64
cosmic-greeter-0.1.0~20240411.23-1.fc40.x86_64
cosmic-workspaces-0.1.0~20240411.23-1.fc40.x86_64
cosmic-comp-0.1.0~20240411.23-1.fc40.x86_64
cosmic-session-0.1.0~20240411.23-1.fc40.x86_64
cosmic-desktop-0.1.0~20240411.23-1.fc40.x86_64
```

**Comment by shawn111** [comment]
It is same as https://github.com/pop-os/cosmic-randr/issues/6

**Comment by shawn111** [comment]
cosmic-desktop-0.1.0~git20240514.00.none-1.fc40.x86_64, this issue is fixed

**Comment by katagawa2023** [comment]
I am having what seems like the same issue.
It recogonized the display for a few seconds, cast the background, allowed me to move them into the proper positions. Then I used my KVM switch to flip over to the other PC and it stopped working all together.
Directly plugged in the HDMI to the Graphics card and it still does not work.
Recognizes that the display is there however the enable display switch quickly flips back to disabled in both directly plugged in HDMI and KVM Switch configurations.

It does not however do this when running POP_OS! When I revert to that from the login screen it works as it has since I installed it.
