### ISSUE TITLE
"Window blinds" after performing certain window management actions

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#499]
After performing window management actions, I sometimes have the entire screen change to a repeated strip showing the top and/or bottom of the screen. Moving the mouse and/or switching workspaces causes the strips to move around and change in size a little bit.

Video of when this happened back in February after unmaximizing a Firefox window with Super-M:

https://github.com/pop-os/cosmic-comp/assets/7199422/e7929869-1038-4df8-9f40-872fa4496574

Photo of this happening just now after moving a window down several workspaces with Super-Shift-Down several times in quick succession:

![1000012015](https://github.com/pop-os/cosmic-comp/assets/7199422/1885b864-40a7-4409-ab27-535fb6bcd3e7)

It's interesting to see that the dock and panel appear to be overlapping within the strips. It's almost like the screen resolution's being set so the height is way lower than it should be.

I understand this is a tricky one since it happens somewhat infrequently, but it is fairly disruptive since it requires restarting cosmic-comp to recover. Let me know if I can get any specific logs or debugging output to help track it down. Here's my system log starting when I resumed from suspend today and ending when I rebooted from a TTY after this happened: [comp-blinds.txt](https://github.com/pop-os/cosmic-comp/files/15408043/comp-blinds.txt)

**Comment by jacobgkau** [comment]
I just had this happen twice in quick succession. Before it started happening, I un-maximized a Firefox window and was attempting to pin it to one side of the screen (all with the mouse). I noticed the text in the tab bar get fuzzy/pixelated, which I initially thought was an Xwayland issue. Then the screen went to blinds.

I did discover a workaround, thankfully. After successfully switching to a TTY, switching back to TTY1 where COSMIC was running made the screen go back to normal. It almost immediately happened a second time, but after switching TTYs and back a second time, it didn't immediately happen a third time. So that makes the issue a little less critical.

**Comment by jacobgkau** [comment]
Scratch that: after using the recovered session for a few minutes, certain keyboard shortcuts stopped working (e.g. Super for opening the launcher and Esc for closing it), and the keyboard eventually stopped working altogether, and finally Firefox stopped responding to mouse inputs, so I had to hard reboot. I'm assuming that instability is related to having had the issue occur.

**Comment by burakturkerdev** [comment]
Same here. But i had something interesting. This happens only in my main display(builtin laptop display).

I literally never had this issue with other two displays.

So i have a two point for this issue.

1- Reason can be HDPI (if comp has any work with pixel density idk)
2- It is only happening in main display

**Comment by ids1024** [comment]
I've also noticed this one an internal display, with 2x scaling, but not the 1x scaling external monitors. Nor does it happen without external monitors connected. So something related to mixed DPI?

Killing cosmic-panel (when starting cosmic-comp manually and not with cosmic-session, so it isn't autorestarted) fixes it.

**Comment by jacobgkau** [comment]
Every time it's happened on the serw13, it's been with the internal LoDPI screen only, but good to know what might help recreate it on other hardware.

**Comment by ids1024** [comment]
Interesting. It isn't necessarily DPI, and it isn't always with multiple monitors? But seems to only happen with the builtin monitor? While on my system, I've only noticed it with external monitors connected. Kind of odd.

I'm having trouble thinking of what might cause this, or where to look for what code would be responsible. Though having some reproducible way to cause it would definitely help.

**Comment by ids1024** [comment]
It seems I can reproduce this fairly consistently with 2 external monitors (but not with only 1?) just opening terminals on an external monitor, switching workspaces, and switching tiling. I haven't identified a specific set of steps that causes it.

I see it repeated 3 times, rather than 5. On the builtin monitor.

Interestingly I see it's using two DRM overlay planes: a `2880x88` plane and a `2880x144` plane. The sizes of the panel and dock. Seems odd, but being related to DRM direct scanout would explain why it varies by computer, monitor, and number of connected monitors...

**Comment by ids1024** [comment]
Okay, actually this seems to be reproducing it consistently for me:
- Run `cosmic-comp`
- Place cursor on external monitor
- Start panel in a terminal with `super-t`, then `cosmic-panel`
- Switch workspaces with `super-2`
- Open terminal with `super-t`
- Exit with `exit`

**Comment by ids1024** [comment]
Setting `planes.overlay = vec![]` in `backend/drm/kms.mod` seems to prevent this, confirming it's related to overlay planes.

**Comment by ids1024** [comment]
Testing this again after https://github.com/pop-os/cosmic-comp/pull/546, it seemed to not be reproducible with the above steps, but then after rebooting it was immediately reproducible?

Interesting. Naturally DRM properties will be reset on reboot, but I wonder what changed to make it not cause issues...

**Comment by Drakulix** [comment]
> Testing this again after #546, it seemed to not be reproducible with the above steps, but then after rebooting it was immediately reproducible?
> 
> Interesting. Naturally DRM properties will be reset on reboot, but I wonder what changed to make it not cause issues...

I sadly can't seem to reproduce this on any of my three machines. Did you happen to capture a `drm_info` log, when the issue happened?

**Comment by ids1024** [comment]
The display I'm seeing this with is 120hz, and I just noticed that I've been seeing this issue with it set to 60hz... and it doesn't seem to be reproducible (at least in the same way) at 120hz.

**Comment by ids1024** [comment]
Seems to be related to partial DRM updates, in particular those that don't update the primary plane.

And presumably some kind of bug in the i915 driver.

**Comment by Drakulix** [comment]
Should be fixed by:
- https://github.com/Smithay/smithay/commit/72b251c20ee2ff4cf85dd1c10e83df0ea8fde3fe
- https://github.com/pop-os/cosmic-comp/commit/2d0f1cbf2be311b91096b2f2332cd7bafabbfde3

Big thanks to @ids1024 and @cmeissl for debugging!

**Comment by jacobgkau** [comment]
I'm hitting this again today on 4748916.

**Comment by jacobgkau** [comment]
Still hitting this on a96394f.

**Comment by jacobgkau** [comment]
This is still happening on Alpha 4 with cosmic-comp 1118aa2.

**Comment by jacobgkau** [comment]
Still happening on a8d12f3 & 99bbd10 today.

**Comment by jacobgkau** [comment]
On the serw13 where this is happening, I'm seeing this in the logs when I recreate the issue:

```
Apr 04 16:11:31 serw13 kernel: i915 0000:00:02.0: [drm] *ERROR* CPU pipe A FIFO underrun: transcoder,
```

Interestingly, at least one time, that line appears in the log file before the issue had fully occurred, then the screen turned to blinds the *next* time I moved the window between workspaces.

When I switch to another TTY and back to fix the issue, I then see these lines appear:

```
Apr 04 16:13:25 serw13 cosmic-comp[3001]: Failed to submit rendering: Failed to submit result for display

                                          Caused by:
                                              0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                              1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                              2: Permission denied (os error 13)
```

and

```
Apr 04 16:13:27 serw13 cosmic-comp[3001]: Failed to destroy old mode property blob: No such file or directory (os error 2)
```

But those last two also appear when switching TTYs on an addw2 where I haven't been able to recreate this issue yet, so I don't think they're related to the issue.

**Comment by jacobgkau** [comment]
This is probably obvious based on the i915 error, but I was playing around with things today, and I found that forcing COSMIC to run on the NVIDIA GPU using the `COSMIC_RENDER_DEVICE` environment variable prevents this issue from occurring. It seems it's something to do with the Intel iGPU (this serw13 contains a Core i9-13900HX). Not sure if the system being hybrid has anything to do with the issue or if it may also present on an Intel-only system.

**Comment by jacobgkau** [comment]
I just confirmed this is still happening on 244c174da454a845f9772c7949071a69a51128f9. However, it took me a few minutes to recreate today. I think a large number of workspaces and/or windows might help to recreate this. I currently have six (seven including the blank one), with 2, 15, 5, 1, 1, and 2 windows on each, respectively, just to give an idea of the scale.

**Comment by jacobgkau** [comment]
Still happening on 7ee48e5.

**Comment by oscardssmith** [comment]
I can also confirm this. I reproduce this 100% of the time on a laptop with a 4k 16:10 display (1.5x scaling) and an external monitor that's 1440p 16:9 (1x scaling)

**Comment by oscardssmith** [comment]
Not sure if it helps, but dmesg (1 of the times) also showed
```
[206283.302886] cosmic-app-libr[2702]: segfault at 18 ip 000062e9fd8f62c0 sp 000071a7537fb730 error 4 in cosmic-app-library[10d32c0,62e9fc980000+163f000] likely on CPU 0 (core 0, socket 0
```

**Comment by ids1024** [comment]
@oscardssmith What specific GPU are you seeing this on?

If you can reproduce it consistently, it could be helpful to see the output of `drm_info` when the issue occurs (and maybe also in as similar a state as possible when the issue isn't occurring. Depending on exactly what triggers it.)

I think I've seen this behavior once or twice on my system with a i7-1255U since the earlier fix, but I don't know any way to get it to happen consistently. (And it used to be a common issue. Before that fix.)

**Comment by oscardssmith** [comment]
I'm on integrated graphics for i7-1185G7. One thing that might be relavent is that the external monitor is connected via a thunderbolt dock (darn you xps-13 lack of ports). Do you want full `drm_info` results or just a part? For me, it prints out ~10 pages of results

**Comment by ids1024** [comment]
You can also try running cosmic-comp with the env var `COSMIC_DISABLE_DIRECT_SCANOUT=1` set. That will likely prevent the issue.

**Comment by jacobgkau** [comment]
@ids1024 Here is `drm_info` immediately before and during the window blinds on `359c3ad` (on the serw13):

[drm-before-blinds.txt](https://github.com/user-attachments/files/20493522/drm-before-blinds.txt)
[drm-with-blinds.txt](https://github.com/user-attachments/files/20493531/drm-with-blinds.txt)

Comparing the two in Meld, I can see the resolution's indeed being set much lower when this happens. Before:

```
Plane 1
    │   ├───Object ID: 41
    │   ├───CRTCs: {0}
    │   ├───Legacy info
    │   │   ├───FB ID: 303
    │   │   │   ├───Object ID: 303
    │   │   │   ├───Size: 1920x1044
    │   │   │   ├───Format: ARGB8888 (0x34325241)
    │   │   │   ├───Modifier: I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS_CC (0x100000000000008)
    │   │   │   └───Planes:
    │   │   │       ├───Plane 0: offset = 0, pitch = 7680 bytes
    │   │   │       ├───Plane 1: offset = 8110080, pitch = 960 bytes
    │   │   │       └───Plane 2: offset = 8142848, pitch = 64 bytes
```

During:

```
    ├───Plane 1
    │   ├───Object ID: 41
    │   ├───CRTCs: {0}
    │   ├───Legacy info
    │   │   ├───FB ID: 303
    │   │   │   ├───Object ID: 303
    │   │   │   ├───Size: 1024x696
    │   │   │   ├───Format: ARGB8888 (0x34325241)
    │   │   │   ├───Modifier: I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS_CC (0x100000000000008)
    │   │   │   └───Planes:
    │   │   │       ├───Plane 0: offset = 0, pitch = 4096 bytes
    │   │   │       ├───Plane 1: offset = 2883584, pitch = 512 bytes
    │   │   │       └───Plane 2: offset = 2895872, pitch = 64 bytes
```

The actual resolution of this display is 1920x1080.

**Comment by jacobgkau** [comment]
Still happening on 48a165d.

**Comment by Drakulix** [comment]
@jacobgkau Could you retest?

A lot of the plane-assignment logic has changed and while I am not certain, that this may have affected your issues, I am still unable to reproduce it on any of my machines. So if you have an old or new at least semi-consistent way to trigger this on current master, that would be highly appreciated.

**Comment by jacobgkau** [comment]
I'm not currently observing this on the same machine where it was regularly occurring before. I've been keeping an eye out for several days while performing the same tasks (using a similar number of windows/workspaces) as before.

I'm good to close this for now. If I spot it again, I can re-open.
