### ISSUE TITLE
Flood of 2+ early vblanks

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#581]
I believe this started happening today with the latest commits. Launching any Xwayland client (VLC, `xeyes`,...) causes a panic and the compositor restarts. Section of log:
```
Jun 27 16:43:12 pop-os cosmic-comp[5024]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /build/cosmic-comp-1Fs6Rw/cosmic-comp-0.1~1719488148~22.04~da9af7a/vendor/smithay/src/xwayland/xwm/surface.rs:865
                                             0: <unknown>
                                             1: <unknown>
                                             2: <unknown>
                                             3: <unknown>
                                             4: <unknown>
                                             5: <unknown>
                                             6: <unknown>
                                             7: <unknown>
                                             8: <unknown>
                                             9: <unknown>
                                            10: <unknown>
                                            11: <unknown>
                                            12: <unknown>
                                            13: <unknown>
                                            14: <unknown>
                                            15: <unknown>
                                            16: <unknown>
                                            17: <unknown>
                                            18: __libc_start_main
                                            19: <unknown>
```
There's also a very large amount of logs (just today 23000+ lines) similar to the following:
```
Jun 27 16:47:07 pop-os cosmic-comp[4664]: got a 2+ early VBlank, 336.045µs until presentation
```

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/5617f3228bcfb83085860790c26595bad8fadec6

**Comment by Drakulix** [comment]
> Jun 27 16:47:07 pop-os cosmic-comp[4664]: got a 2+ early VBlank, 336.045µs until presentation

Good to know, will tune that down. Though that is slightly worrying, does your system appear to be responsive?

**Comment by git-f0x** [comment]
Seems reasonably responsive, at least for now.

**Comment by git-f0x** [comment]
```
Thu 2024-06-27 17:20:01.592048 CEST [s=fd0f07d555c84ae7a918178d88a43821;i=78e6f;b=07cd5e2a32cc4698ac4964d8a4d54a7b;m=788e83f;t=61be0aa27544c;x=5869f3253ee17687]
    PRIORITY=3
    TARGET=cosmic_comp::backend::kms::surface::timings
    CODE_FILE=src/backend/kms/surface/timings.rs
    CODE_LINE=232
    SYSLOG_IDENTIFIER=cosmic-comp
    _TRANSPORT=journal
    _UID=1000
    _GID=1000
    _COMM=cosmic-comp
    _EXE=/usr/bin/cosmic-comp
    _CMDLINE=cosmic-comp
    _CAP_EFFECTIVE=0
    _SELINUX_CONTEXT=unconfined
    _AUDIT_SESSION=2
    _AUDIT_LOGINUID=1000
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/session-2.scope
    _SYSTEMD_SESSION=2
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_UNIT=session-2.scope
    _SYSTEMD_SLICE=user-1000.slice
    _SYSTEMD_USER_SLICE=-.slice
    _MACHINE_ID=c2f32144de4a29a9226739aa65c8aee3
    _HOSTNAME=pop-os
    MESSAGE=got a 2+ early VBlank, 230.083µs until presentation
    _BOOT_ID=07cd5e2a32cc4698ac4964d8a4d54a7b
    _SYSTEMD_INVOCATION_ID=f0c1299a76a34abc82cb22a8661f0494
    _PID=1572
    F_LAST_PRESENTATION_TIME=126.412784s
    F_NOW=126.412493917s
    _SOURCE_REALTIME_TIMESTAMP=1719501601592048
```
```
Thu 2024-06-27 17:20:13.575074 CEST [s=fd0f07d555c84ae7a918178d88a43821;i=7925c;b=07cd5e2a32cc4698ac4964d8a4d54a7b;m=83fbfc7;t=61be0aade2bd4;x=da8b9f8ac60492d2]
    PRIORITY=3
    TARGET=cosmic_comp::backend::kms::surface::timings
    CODE_FILE=src/backend/kms/surface/timings.rs
    CODE_LINE=232
    SYSLOG_IDENTIFIER=cosmic-comp
    _TRANSPORT=journal
    _UID=1000
    _GID=1000
    _COMM=cosmic-comp
    _EXE=/usr/bin/cosmic-comp
    _CMDLINE=cosmic-comp
    _CAP_EFFECTIVE=0
    _SELINUX_CONTEXT=unconfined
    _AUDIT_SESSION=2
    _AUDIT_LOGINUID=1000
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/session-2.scope
    _SYSTEMD_SESSION=2
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_UNIT=session-2.scope
    _SYSTEMD_SLICE=user-1000.slice
    _SYSTEMD_USER_SLICE=-.slice
    _MACHINE_ID=c2f32144de4a29a9226739aa65c8aee3
    _HOSTNAME=pop-os
    _BOOT_ID=07cd5e2a32cc4698ac4964d8a4d54a7b
    _SYSTEMD_INVOCATION_ID=f0c1299a76a34abc82cb22a8661f0494
    _PID=1572
    F_LAST_PRESENTATION_TIME=138.396063s
    MESSAGE=got a 2+ early VBlank, 475.447µs until presentation
    F_NOW=138.395527553s
    _SOURCE_REALTIME_TIMESTAMP=1719501613575074
```
These are the first and last sections (of 31k lines) with that command.

**Comment by Drakulix** [comment]
> F_LAST_PRESENTATION_TIME=126.412784s
> F_NOW=126.412493917s

So looking at cosmic-comps code, something has to be wrong here and I very curious what.
The difference between these two values is `0.00029008299s`, so sub-milliseconds.

The code triggering this message:
```
if now <= last_presentation_time {
    // Got an early VBlank.
    let orig_now = now;
    now += Duration::from_nanos(refresh_interval_ns);

    if now < last_presentation_time {
        // Not sure when this can happen.
        error!(
            now = ?orig_now,
            ?last_presentation_time,
            "got a 2+ early VBlank, {:?} until presentation",
            last_presentation_time - now,
        );
            now = last_presentation_time + Duration::from_nanos(refresh_interval_ns);
        }
    }
}
```

Now we should pass the first if-condition. The hardware can indeed report us a presentation time in the future, if it knows when the next scanout will happen. But then we add the `refresh_interval` in other words the interval between frames to target the next frame.

Even on a 360hz monitor this is 2.78ms, so this should comfortably bring `now` higher than `last_presentation_time`. So how did the code mess this up to get into the second if-loop?

`now` apparently (calculating back from our "until presentation"-value) was `126.412553917`, for the second if loop. So `126.412553917 - 126.412493917`, which is apparently `0.0000599`, so less than a millisecond? That can't be right.

**Comment by Drakulix** [comment]
Yeah I am just not calculating the refresh_interval correctly. :woman_facepalming: 

Thanks for that little comment. Apparently the math works out to not log something on my systems, so I wouldn't have noticed otherwise.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/8da3ac6d75197acce5d3373ddd97548b5eafee37. Please report back, if the problem didn't go away.

**Comment by git-f0x** [comment]
Will test it as soon as it's in the repos.

**Comment by git-f0x** [comment]
Seems to be fixed!

**Comment by khoidauminh** [comment]
Hello, I'm using `cosmic-session-git` on Archlinux and I'm still getting these log spams whenever adaptive sync is active:

```
Thg 6 13 23:57:29 kdpc cosmic-comp[55657]: got a 2+ early VBlank, 7.090809ms until presentation
```

The logs seem to disappear when I set my monitor rate to 60hz. The spam appears when I set my monitor to 144hz, and Adaptive sync to Automatic or Always. When Adaptive sync is always, the log constantly spams the message, and for Automatic, it's when I run an app in fullscreen. 

These are my outputs of the above command:
```
Sat 2026-06-13 23:57:43.826303 +07 [s=9f38de68c0794e7c970e0ed232b9a758;i=f251c;b=577297619d794c74ad8ee906e5241cd4;m=8d12ce63;t=654257df26d6d;x=7a40ff204a3c3139]
    PRIORITY=3
    TARGET=cosmic_comp::backend::kms::surface::timings
    CODE_FILE=src/backend/kms/surface/timings.rs
    CODE_LINE=304
    SYSLOG_IDENTIFIER=cosmic-comp
    _TRANSPORT=journal
    _UID=1000
    _GID=1000
    _COMM=cosmic-comp
    _EXE=/usr/bin/cosmic-comp
    _CMDLINE=cosmic-comp
    _CAP_EFFECTIVE=0
    _AUDIT_LOGINUID=1000
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_SLICE=user-1000.slice
    _SYSTEMD_USER_SLICE=-.slice
    _MACHINE_ID=34ac259858db4435bcffe7e9bed9fbe4
    _HOSTNAME=kdpc
    _RUNTIME_SCOPE=system
    _BOOT_ID=577297619d794c74ad8ee906e5241cd4
    _AUDIT_SESSION=29
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/session-29.scope
    _SYSTEMD_SESSION=29
    _SYSTEMD_UNIT=session-29.scope
    _SYSTEMD_INVOCATION_ID=6f81611a75d24d45a8b22acad7e1e032
    _PID=55657
    F_LAST_PRESENTATION_TIME=2366.828921s
    MESSAGE=got a 2+ early VBlank, 2.536112ms until presentation
    F_NOW=2366.81944054s
    _SOURCE_REALTIME_TIMESTAMP=1781369863826303
```

```
Sun 2026-06-14 00:00:40.887742 +07 [s=9f38de68c0794e7c970e0ed232b9a758;i=f2919;b=577297619d794c74ad8ee906e5241cd4;m=97a08b72;t=6542588802a7d;x=bf641a9d32561653]
    PRIORITY=3
    TARGET=cosmic_comp::backend::kms::surface::timings
    CODE_FILE=src/backend/kms/surface/timings.rs
    CODE_LINE=304
    SYSLOG_IDENTIFIER=cosmic-comp
    _TRANSPORT=journal
    _UID=1000
    _GID=1000
    _COMM=cosmic-comp
    _EXE=/usr/bin/cosmic-comp
    _CMDLINE=cosmic-comp
    _CAP_EFFECTIVE=0
    _AUDIT_LOGINUID=1000
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_SLICE=user-1000.slice
    _SYSTEMD_USER_SLICE=-.slice
    _MACHINE_ID=34ac259858db4435bcffe7e9bed9fbe4
    _HOSTNAME=kdpc
    _RUNTIME_SCOPE=system
    _BOOT_ID=577297619d794c74ad8ee906e5241cd4
    _AUDIT_SESSION=29
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/session-29.scope
    _SYSTEMD_SESSION=29
    _SYSTEMD_UNIT=session-29.scope
    _SYSTEMD_INVOCATION_ID=6f81611a75d24d45a8b22acad7e1e032
    _PID=55657
    F_LAST_PRESENTATION_TIME=2543.894791s
    MESSAGE=got a 2+ early VBlank, 6.973658ms until presentation
    F_NOW=2543.880872994s
    _SOURCE_REALTIME_TIMESTAMP=1781370040887742
```
