### ISSUE TITLE
Fullscreen window can lose focus without obvious indication

### ISSUE THREAD

**Issue by KoreshKrasa** [pop-os/cosmic-comp#696]
Currently fullscreen window can lose focus if Super+Arrow is pressed but focused window is not shown. Similar happening with maximized window if tiling is enabled. I think in those cases if window is not raised to top than fullscreen/maximized window should not lose focus.

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/f9d39144ede8f873736d6c6f3da3df22fc5bc35b and https://github.com/pop-os/cosmic-comp/commit/7660f7aaa9d0730f6cfd72c36f106fc4e514ac06

**Comment by drazil100** [comment]
If you move a window between workspaces (Shift+Super+Arrow) to a workspace with a fullscreen window the focus appears to be on the window you just moved. Super+M fullscreens the just moved window on top of the previous window while the old window is still fullscreened.

**Comment by Drakulix** [comment]
> @Drakulix not sure if this is in line with design plans but maybe full screen windows can be moved to separate workspace exclusive to this full screen window. E.g. if user have 3 worksapces and full screen window opened from first one it will insert separate ful lscreen workspace like: 1,2,3 -> 1,f1,2,3. If more full screen windows are spawned they will go like: 1, f2, f1, 2, 3. And then compositor should just restrict movement of other windows to full screen workspace. Then It will only require launcher to be able to penetrate full screen to switch applications.

That sounds a lot like how MacOS handles fullscreen. Afaik this was considered at some point, but definitely doesn't represent our current designs. Ping for @pop-os/ux just in case we want to reconsider this in general. But in any case the focus issues described in this issue should be fixed regardless.

**Comment by git-f0x** [comment]
IMO, a fullscreen window should behave mostly like any other window, with its own focus layer (e.g. if an app is opened in the same workspace as the fullscreen window, it would display over it, and would go under if the fullscreen window is focused), or the fullscreen window should minimize when it loses focus to another app (though this might be worse in case a sticky window of another app is used).
Though I'm not sure if there are other use cases for fullscreen windows, other than for gaming or increasing screen real-estate.
Tiling should also probably have its own focus layer (shared by all tiled apps), so that a floating app can go behind the tiled windows when it's unfocused.

**Comment by WatchMkr** [comment]
These issues appear to be fixed. Leaving the issue open for a bit in case anyone is still seeing these.
