### ISSUE TITLE
Right click context menu hidden behind other dialogs in chrome based browsers

### ISSUE THREAD

**Issue by DW8Reaper** [pop-os/cosmic-comp#886]
I specifically use Brave and it happens there but I also tested it in Chromium, the specific versions I tried:

- Brave, flatpak version 1.70.119 `com.brave.Browser`
- Ungoogled Chromium, flatpak version 129.0.6668.70-1-1 `io.github.ungoogled_software.ungoogled_chromium`

I attached a video, if you right click on a bookmark all is well and the context menu works as expected. If you open a bookmark folder which opens list of links it has in a dialog and then right click one of those the new context menu renders behind the folder items dialog instead of on top.

Cosmic comp version:

> Package: cosmic-comp
> Version: 0.1~1727082801~22.04~afdb656
> Priority: optional
> Section: x11
> Maintainer: Victoria Brekenfeld <victoria@system76.com>
> Installed-Size: 24.7 MB
> Depends: libc6 (>= 2.35), libgbm1 (>= 21.3.0~rc1), libgcc-s1 (>= 4.2), libinput10 (>= 1.19.1), libpixman-1-0 (>= 0.30.0), libseat1 (>= 0.5.0), libudev1 (>= 183), libxkbcommon0 (>= 0.5.0), libegl1, libwayland-server0
> Recommends: cosmic-session, libgl1-mesa-dri
> Homepage: https://github.com/pop-os/cosmic-comp
> Download-Size: 7,850 kB
> APT-Manual-Installed: no
> APT-Sources: http://apt.pop-os.org/release jammy/main amd64 Packages
> Description: Wayland compositor of pop-os cosmic shell

https://github.com/user-attachments/assets/e4dc2116-7d56-4df3-b648-8249dabef42f

**Comment by Drakulix** [comment]
Fixed by 0095b6d5

**Comment by DW8Reaper** [comment]
Can confirm this works now for me, tested with cosmic-comp `0.1~1755788989~24.04~f2813f0`

**Comment by jbaribeault** [comment]
The fix in 0095b6d resolved this for the **XWayland** case by reversing the override-redirect window stack order so newer windows render above older ones. That correctly fixed Brave and Chromium when running under XWayland.

However, the issue persists when those browsers run under **native Wayland** (`--ozone-platform=wayland`), which is increasingly common. In that mode, Chromium creates tooltip and transient popup surfaces as parentless `xdg_toplevel` surfaces — with empty `app_id`, empty `title`, and no `set_parent` call — rather than `xdg_popup` surfaces as the protocol requires. Override-redirect stacking doesn't apply here at all since these are Wayland-native surfaces.

A fix for the native Wayland case is documented and patched in #2301, which covers the full symptom set: surfaces appearing behind the parent window, keyboard focus stealing causing immediate surface destruction, and spurious dock entries. Confirmed working on Microsoft Edge 147 and Chromium 134 (snap) on cosmic-comp `0.1~1776181377~24.04~4df9519`.
