### ISSUE TITLE
Incorrect GPU selection for session

### ISSUE THREAD

**Issue by flukejones** [pop-os/cosmic-comp#913]
I have a new laptop with AMD and NVIDIA GPU. The AMD gpu is the iGPU. However there are a few issues:

1. The Nvidia GPU is before the AMD on the PCI bus
```
65:00.0 VGA compatible controller: NVIDIA Corporation AD106M [GeForce RTX 4070 Max-Q / Mobile] (rev a1)
66:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Strix [Radeon 880M / 890M] (rev c1)
```

2. The Nvidia GPU is marked as boot_vga

3. This causes the dGPU to be in consistent use and never suspend. It will suspend if switched to a TTY and desktops stopped.

The issue isn't solely cosmic-comp. Gnome is affected also. However if I work around the issue with `nvidia_drm.modeset=0` this prevents gnome grabbing the card, but makes cosmic crash as it tries to use `card0` with now doesn't have DRM ability.

Related issue on [`drm/amd`](https://gitlab.freedesktop.org/drm/amd/-/issues/3673)

**Comment by Quackdoc** [comment]
temporary fix should be `COSMIC_RENDER_DEVICE=/dev/dri/renderD1##` env var? I believe `COSMIC_RENDER_AUTO_ASSIGN=y` may also be warranted.

**Comment by flukejones** [comment]
Unfortunately that does not help. Still selects incorrect gpu

**Comment by superm1** [comment]
Since the same thing came up on mutter I did have a [proposal](https://gitlab.gnome.org/GNOME/mutter/-/issues/3746) there for them to better pick things.  Maybe cosmic can do something similar.

**Comment by flukejones** [comment]
I can confirm that using the udev rule changes as @superm1 suggests in the link above does indeed fix the issues I've experienced in Gnome.

I also discovered that Nvidia 560 driver was causing further issues that maybe masked some things adversely, so I will retest cosmic with 550 driver.

**Comment by flukejones** [comment]
Umm, yeah.. Have to start cosmic with `COSMIC_RENDER_DEVICE=/dev/dri/renderD128 cosmic-session` and with nvidia driver 550 the dgpu suspends. But there are too many things going on for me to adequately track while also trying to work. Some notes:

- Nvidia 550
- kernel 6.12-rc3
- Applied https://lore.kernel.org/linux-pci/20241014152502.1477809-1-superm1@kernel.org/T/#u
- zed editor fails to load (I will get logs another time)
- some things needed `DRI_PRIME=0` to run at all and I think those were on nvidia

It seems like a whole lot of Linux land is built on certain assumptions that this laptop has kicked the door in on.

**Comment by superm1** [comment]
> Umm, yeah.. Have to start cosmic with COSMIC_RENDER_DEVICE=/dev/dri/renderD128 cosmic-session

I guess if a similar approach to Gnome is used you would need to come up with a way to associate the render device to the PCI ID and the DRM card with eDP connected to the same PCI ID to decide which render node to use.

**Comment by hgaiser** [comment]
I'm having a similar issue on my laptop, however my NVIDIA dGPU is not marked as `boot_vga`. I get the following:

```sh
$ fuser -v /dev/dri/render*
                     USER        PID ACCESS COMMAND
/dev/dri/renderD128: hgaiser   26880 F...m Xwayland
                     hgaiser   27064 F...m cosmic-panel
                     hgaiser   27068 F...m cosmic-workspac
                     hgaiser   27079 F...m xdg-desktop-por
                     hgaiser   27184 F...m cosmic-ext-appl
                     hgaiser   27547 F...m wezterm-gui
                     hgaiser   27805 F...m firefox
/dev/dri/renderD129: hgaiser   26865 F.... cosmic-comp
```

Interestingly there are other cosmic binaries that correctly use the AMD GPU, only cosmic-comp uses the NVIDIA dGPU.

I added `export COSMIC_RENDER_DEVICE=/dev/dri/renderD128` to `/usr/bin/start-cosmic` but it doesn't seem to change anything.

@flukejones where did you add that variable? Or did you run cosmic from commandline?

**Comment by Drakulix** [comment]
> I'm having a similar issue on my laptop, however my NVIDIA dGPU is not marked as `boot_vga`. I get the following:
> 
> ```shell
> $ fuser -v /dev/dri/render*
>                      USER        PID ACCESS COMMAND
> /dev/dri/renderD128: hgaiser   26880 F...m Xwayland
>                      hgaiser   27064 F...m cosmic-panel
>                      hgaiser   27068 F...m cosmic-workspac
>                      hgaiser   27079 F...m xdg-desktop-por
>                      hgaiser   27184 F...m cosmic-ext-appl
>                      hgaiser   27547 F...m wezterm-gui
>                      hgaiser   27805 F...m firefox
> /dev/dri/renderD129: hgaiser   26865 F.... cosmic-comp
> ```


This shouldn't be an issue. `cosmic-comp` does nothing but holding an open drm-device (which we need to evaluate if any outputs are connected to it), but it doesn't initialize any resources, that keep the GPU alive, if no applications access it and no output is connected to it.

**Comment by hgaiser** [comment]
Thanks for the quick reply, that makes sense. Do you have any tips on how to debug why my dGPU doesn't go idle when I'm only using the eDP output (laptop screen)?

**Comment by Drakulix** [comment]
> Thanks for the quick reply, that makes sense. Do you have any tips on how to debug why my dGPU doesn't go idle when I'm only using the eDP output (laptop screen)?

That depends on your dGPU and specific system. Since you seem to be using an nVidia GPU, your options are quite limited, given the driver is a black box. So all you have to go by is this bit of documentation: http://us.download.nvidia.com/XFree86/Linux-x86_64/560.35.03/README/dynamicpowermanagement.html

Some systems might also have buggy firmware, e.g. I have a personal machine that will leave the dGPU hanging in an active state, if ever during the current boot an external output was connected to it. If I restarted it afterwards it powers down the GPU as expected. I figured this out by observation, as there isn't much else you can do on a closed source firmware system.

**Comment by flukejones** [comment]
Both KDE and Gnome confirmed fixed:
- https://gitlab.gnome.org/superm1/mutter/-/commit/dc565bc2028b796e89598e0b8b20451a39d9d2ff
- https://bugs.kde.org/show_bug.cgi?id=494749
-

**Comment by Drakulix** [comment]
> Both KDE and Gnome confirmed fixed:
> 
>     * https://gitlab.gnome.org/superm1/mutter/-/commit/dc565bc2028b796e89598e0b8b20451a39d9d2ff
> 
>     * https://bugs.kde.org/show_bug.cgi?id=494749

That might break, once we have proper dynamic MUX support, but I guess is a sensible default for now. Thanks for these references.

**Comment by superm1** [comment]
> That might break, once we have proper dynamic MUX support, 

Yeah; but I feel this is a long way's out and will require compositor overhaul everywhere.  So yeah I think it's better to help the now.

**Comment by hgaiser** [comment]
> > Thanks for the quick reply, that makes sense. Do you have any tips on how to debug why my dGPU doesn't go idle when I'm only using the eDP output (laptop screen)?
> 
> That depends on your dGPU and specific system. Since you seem to be using an nVidia GPU, so your options are quite limited, given the driver is a black box. All you have to go by is this bit of documentation: http://us.download.nvidia.com/XFree86/Linux-x86_64/560.35.03/README/dynamicpowermanagement.html
> 
> Some systems might also have buggy firmware, e.g. I have a personal machine that will leave the dGPU hanging in an active state, if ever during the current boot an external output was connected to it. If I restart it afterwards it powers down the GPU as expected. I figured this out by observation, as there isn't much else you can do on a closed source firmware system.

Small update: this seems to be an nvidia driver issue. At least, switching to nouveau makes the GPU go into D3cold state as expected.

**Comment by flukejones** [comment]
Is there any movement on this? It's something of a blocker. Also worth mentioning that the battery applet for GPU use shows the igpu as primary.

**Comment by flukejones** [comment]
> > I have to force `COSMIC_RENDER_DEVICE=/dev/dri/renderD128` which is the Nvidia GPU, but this GPU isn't in use by cosmic (it suspends).. All a bit confusing.
> 
> So why do you not force the iGPU here? That would do exactly the same thing as adjusting the selection logic.

It had errors of unsupported something or other. I'll try get logs at some point. The errors only happen if I set this.

> Also just because a GPU isn't used by cosmic, doesn't mean it isn't considered the boot gpu. It may still suspend, if no output is directly connected to it and no application is using it.

Not sure what you mean here.

> (Right now it also assumes the boot_vga gpu is the primary one and considers every other secondary, but that actually has no effect on anything, the visualization is just wrong.)

There are some kernel patches coming down the pike that should address the incorrect setting of boot_vga attribute. In general though I got the impression from LKML comments and on amd/drm that this wasn't a good or reliable thing to use as some ACPI do not have vga (a better explanation is beyond me sorry)

The solution that both KDE and Gnome have adopted and merged is to check the screens attached, and the GPU with EDP screen is set as the iGPU/primary GPU.

**Comment by Drakulix** [comment]
> It had errors of unsupported something or other. I'll try get logs at some point. The errors only happen if I set this.

That would be very helpful. Given said variable does nothing but overriding the automatic selection logic, adjusting the code as requested above would likely raise the same error on your system. So we need to fix this one way or another.
 
> > Also just because a GPU isn't used by cosmic, doesn't mean it isn't considered the boot gpu. It may still suspend, if no output is directly connected to it and no application is using it.
> 
> Not sure what you mean here.

The GPU suspending doesn't mean cosmic doesn't consider it the default.

> The solution that both KDE and Gnome have adopted and merged is to check the screens attached, and the GPU with EDP screen is set as the iGPU/primary GPU.

Yes, I know. And we should change that as well.

**Comment by flukejones** [comment]
I need some instruction on how best to provide logs. Currently with alpha 5 I still get issues, this time round I get a crash loop and the fix is to set `COSMIC_RENDER_DEVICE=/dev/dri/renderD128` in my `/etc/environment`

Once done everything seems to be rock solid.

**Comment by Drakulix** [comment]
> I need some instruction on how best to provide logs. Currently with alpha 5 I still get issues, this time round I get a crash loop and the fix is to set `COSMIC_RENDER_DEVICE=/dev/dri/renderD128` in my `/etc/environment`
> 
> Once done everything seems to be rock solid.

What issues do you get and could you post a log of `journalctl --user _COMM=cosmic-comp` after unsetting `COSMIC_RENDER_DEVICE` again?

**Comment by flukejones** [comment]
Results of no env set: [cosmic-crashes.txt](https://github.com/user-attachments/files/18416758/cosmic-crashes.txt)

**Comment by jipiboily** [comment]
Hey folks! Thanks for looking into that so far! I am in the same boat as @flukejones (with a slightly different laptop, I think...I have an Asus Proart P16 which has an HX 370 CPU with iGPU, and a 4070 mobile, and I think @flukejones have a G16 or G14 2024, IIRC from asusctl stuff he mentioned...).

I've tried a bunch of things, and nothing seems to work so far to force the iGPU to be the default...and prime doesn't work.

I'm not a kernel or Rust dev (but I'm a dev), but I'm happy to help with at least testing or whatnot.

How can I help so that we can get that moving?

Would be great to pick a default GPU and the fixes for Gnome and KDE seems like a good first step....I think?

Let me know how I can help :)

For context, I run Cachy OS, fully up to date, with the "latest" Cosmic alpha (as in the released one, not the git or Chaotic AUR one).

**Comment by flukejones** [comment]
> This looks like you messed with env variables (e.g. with `GBM_BACKEND`) somewhere. Doing this breaks driver selection for multiple gpus.

Even without this (clean install) the GPU selection is ~~still~~ was an issue.

I've tried the latest alpha builds and it looks like the correct gpu is selected fro most things, but some parts of cosmic suite seem to keep the dGPU active still. I'll try to get some time this week to look further.

Out of interest I looked at nodes to verify order:
```
❯ drm_info -j | jq 'with_entries(.value |= .driver.desc)'
{
  "/dev/dri/card1": "NVIDIA DRM driver",
  "/dev/dri/card0": "AMD GPU"
}

❯ ls -l /sys/class/drm/renderD*/device/driver
/sys/class/drm/renderD128/device/driver:
lrwxrwxrwx    0 root 21 May 10:36 0000:66:00.0 -> ../../../../devices/pci0000:00/0000:00:08.1/0000:66:00.0
.-w------- 4.1k root 21 May 10:36 bind
lrwxrwxrwx    0 root 20 May 21:48 module -> ../../../../module/amdgpu
.-w------- 4.1k root 21 May 10:36 new_id
.-w------- 4.1k root 21 May 10:36 remove_id
.-w------- 4.1k root 21 May 10:36 uevent
.-w------- 4.1k root 21 May 10:36 unbind

/sys/class/drm/renderD129/device/driver:
lrwxrwxrwx    0 root 21 May 10:36 0000:65:00.0 -> ../../../../devices/pci0000:00/0000:00:03.1/0000:65:00.0
.-w------- 4.1k root 21 May 10:36 bind
lrwxrwxrwx    0 root 20 May 21:48 module -> ../../../../module/nvidia
.-w------- 4.1k root 21 May 10:36 new_id
.-w------- 4.1k root 21 May 10:36 remove_id
.-w------- 4.1k root 21 May 10:36 uevent
.-w------- 4.1k root 21 May 10:36 unbind
```

**Comment by flukejones** [comment]
Recent updates seem to have smoothed out a lot of things for me. Desktop is running crisp at 60 and 240hz, plus GPU selection issue looks to be cleared up.

I'm not sure what steam is doing, but it activates dGPU regardless of what the desktop entry contains for gpu selection, or `DRI_PRIME` setting. I don't know if cosmic can force something here? In any case I filed the issue at https://github.com/ValveSoftware/steam-for-linux/issues/11967

**Comment by Drakulix** [comment]
> Recent updates seem to have smoothed out a lot of things for me. Desktop is running crisp at 60 and 240hz, plus GPU selection issue looks to be cleared up.

Thanks, closing this for now then.

GPU selection was fixed in #1429 (though it might need #1445 to be consistent) and lots of profiling work recently addressed various problems with high-refresh rates. Happy to hear, that it pays off. :)

**Comment by Drakulix** [comment]
> I'm not sure what steam is doing, but it activates dGPU regardless of what the desktop entry contains for gpu selection, or DRI_PRIME setting. I don't know if cosmic can force something here? In any case I filed the issue at https://github.com/ValveSoftware/steam-for-linux/issues/11967

Quick note on this: `DRI_PRIME` does nothing, if one of your GPUs is running the nvidia driver. It is a flag respected by mesa-drivers for nvidia you need to use the `__NV_PRIME_RENDER_OFFLOAD` variable and the likes. But that should be done by cosmic-launcher/app-library/panel correctly, if you select the GPU through the context menu. So if that still doesn't work it is indeed likely either a driver or steam bug.

**Comment by flukejones** [comment]
Impressive work by everyone.

For some reason `DRI_PRIME` does affect the order of GPU in steams list and it selects the first one as primary. I don't see a GPU selection in any menus. But this might be off-topic here, I can file an issue in the relevant place if you point me.

**Comment by Drakulix** [comment]
Order of gpus enumerated would be part of a vulkan layer provided by mesa.

That *might* influence a few vulkan-based clients.

**Comment by prasannavl** [comment]
This is still an issue. I see that a kernel patch is being applied on pop os's kernel, but I'm running cosmic on Debian and this rather makes me stay with sway or gnome due to the following reasons:
-  The USB-C / HDMI ports for external monitors are connected directly to Nvidia (as a consequence you can't just switch Integrated only mode).
-  When on battery, this kills the laptop in a fraction due to apps like cosmic-term, cosmic-files, etc all picking Nvidia when on Hybrid instead of Integrated. 


## Distribution friendly solution

- A better solution would be to take a page out of gnome. Gnome allows it to be tagged via udev. If a `mutter-device-preferred-primary` is marked, that's the one that's used. 

Ref: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1562

If the kernel solution is being upstream, that might great, however, having a mechanism to control it like what gnome added would help in scenarios where there are multiple `boot_vga` marks / avoid confusion while also providing a more immediate workaround for incorrectly marked devices.

**Comment by Drakulix** [comment]
The issue in cosmic-comp has been addressed, if you are still running into applications launching on the wrong gpu, that is a bug in the switcheroo-control daemon, which isn't maintained by us and packaged by your distribution of choice.

Nothing we can do here.

**Comment by prasannavl** [comment]
Hi @Drakulix, it is true that `switcheroo-control` daemon is the one that mislabels the gpu (technically not the daemon as it simply matches what's seen from kernel) and uses the incorrect one as default. 

This should be fixed upstream in the ideal world and hopefully does. However, note that other desktops like gnome / kde appear to solve it in the compositor since it's just easier and the issue is significant pain point enough on machines with multiple GPU. 

Just noting that it would be helpful to add such paths to make the user experience better and match it with the other desktops rather than purely depending on switcheroo-control (even though I agree, this is the ideal one).

**Comment by petegee** [comment]
Another data point on effectively identical hardware — ASUS ProArt P16
(H7606), Ryzen AI 9 HX 370 with Radeon 890M iGPU + RTX 4070 Mobile, hybrid mode.

Worth noting that on **no-MUX** laptops like this one, GPU selection is not
only a power/suspend concern. The internal panel is wired to the iGPU, so
`boot_vga=1` is the AMD device and cosmic-comp always renders there.

On this machine the 890M triggers repeated amdgpu ring timeouts, MES control
path failures and MODE2 resets under cosmic-comp (details and logs in #2149).
The standard mitigations — `amdgpu.cwsr_enable=0`, `amdgpu.dcdebugmask=0x10`,
current linux-firmware, COSMIC 1.4.0, kernels 6.17.9 and 7.0.11 — do not stop
them. Under GNOME on the same kernel the machine is stable, and the problem is
in any case avoidable there by switching to NVIDIA mode.

Because there is no way to select the render GPU under COSMIC, there is no
equivalent workaround here, so the GPU selection limitation turns a mitigable
bug into a hard blocker. A supported render-GPU override (or a way to override
the `boot_vga` default) would make this hardware usable.

https://github.com/pop-os/cosmic-comp/issues/2149#issuecomment-5042236235

**Comment by Drakulix** [comment]
> Worth noting that on **no-MUX** laptops like this one, GPU selection is not only a power/suspend concern. The internal panel is wired to the iGPU, so `boot_vga=1` is the AMD device and cosmic-comp always renders there.

If you have no MUX, then the internal display is always connected to the AMD iGPU, meaning cosmic-comp has to use it to display anything. No matter if it renders the image on the iGPU or dGPU.

> On this machine the 890M triggers repeated amdgpu ring timeouts, MES control path failures and MODE2 resets under cosmic-comp (details and logs in [#2149](https://github.com/pop-os/cosmic-comp/issues/2149)). The standard mitigations — `amdgpu.cwsr_enable=0`, `amdgpu.dcdebugmask=0x10`, current linux-firmware, COSMIC 1.4.0, kernels 6.17.9 and 7.0.11 — do not stop them. Under GNOME on the same kernel the machine is stable, and the problem is in any case avoidable there by switching to NVIDIA mode.

If the nvidia mode switches the internal display to the nvidia gpu (which would indicate you have a mux), then cosmic-comps logic would consider the nvidia gpu primary, as it would be the one connected to the internal display.
