### ISSUE TITLE
[BUG] Unable to click buttons at the bottom of windows. 

### ISSUE THREAD

**Issue by Zakadius123** [pop-os/cosmic-comp#961]
COSMIC-comp version: 0.1~1729786945~24.04~65a5470

In many apps including Krita, Firefox, Nheko and Mullvad Browser, I am unable to interact with buttons at the bottom of the windows. I think this is because the resize function is taking priority when it shouldn't.

I did not see this issue in a few apps like Strawberry Music Player and Zen Browser.

**Comment by Drakulix** [comment]
This is fixed in eb64fdaf8fe4f5e6957a35e74004b183acc905c8

**Comment by Tiedye** [comment]
I'm still getting this, has this been released yet?

**Comment by Drakulix** [comment]
Yes, the alpha 3 release included this as well as any git builds since the linked commit. What version are you running?

**Comment by Zakadius123** [comment]
I'm currently on Alpha 3 (Cosmic-comp version 0.1~1730890885~24.04~641bb75), most of my software work fine when clicking in the bottom, however I'm still seeing the same behavior on Firefox and Mullvad. As far as I can tell these are the only two affected. Though for some weird reason Zen doesn't have this issue despite being based on Firefox.

**Comment by Zakadius123** [comment]
Actually small update. It seems to be related to stacked window. When not stacked I can click at the bottom of both FF/Mullvad but when stacked I can't. This also affect other app I add to the stack.

**Comment by Tiedye** [comment]
On popos, apt list:
```
cosmic-comp/jammy,now 0.1~1731512023~22.04~8d5541b amd64 [installed,automatic]
```
I also am using stacked windows 100% of the time and can confirm it only happens when using stacked windows
